### ISSUE TITLE
plotSection of mdf calculated from (close to) uniform odf

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#146]
When I try to use plotSection() on an mdf and plot axisAngle sections, the plot looks suspiciously wrong.
```
cs=crystalSymmetry('321')
odf=uniformODF(cs)
mdf=calcMDF(odf)
plotSection(mdf,'axisAngle','volumeScaling',false)
```
![plotssetion_mdf](https://cloud.githubusercontent.com/assets/11697557/12490666/fa61f12a-c076-11e5-9dee-b93091aeac74.png)
These are 60° sections, so they should not be so close to 1 everywhere.

Cheers,
Rüdiger

Update:
If the following does not crash (see #147 )
```
odf=unimodalODF(orientation('Euler',[0 0 0]*degree,cs),'halfwidth',90*degree)
mdf=calcMDF(odf)
plotSection(mdf,'axisAngle','volumeScaling',false)
```
the corresponding  plot looks sort of different, although I'm not entirely sure, if this looks right.
![plotssection_kernelmdf](https://cloud.githubusercontent.com/assets/11697557/12491247/5be4d8ce-c07a-11e5-9ccb-88f08157a209.png)

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

I think the first is only a scaling issue.
```matlab
CLim(gcm,[0,1])
```
should solve the issue.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
as far as I understand the plot, the density is everywhere very close to 1, but this should not be the case. Is that related to #147 with calcMDF failing for uniform distributions?
Cheers,
Rüdiger

**Comment by kilir** [comment]
Using mtex-4.2.2 (as of commit/8670d75e5f08bf2f979d54a661ef7c868a9772a7)
```
odf=uniformODF(cs)
mdf=calcMDF(odf)
plotSection(mdf,'axisAngle','volumeScaling',false)
mtexColorbar
```
looks like that (for 60 degree section to make sure that there should be some deviation from 1):

![plotsection](https://cloud.githubusercontent.com/assets/11697557/12535627/aaf6959a-c289-11e5-8a87-96004b196077.jpg)

I'm still not sure if it is supposed to look like that.
All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

I think that the MDF in the sections is close to 1 is correct.

a) Imagine all these angle sections overlayed would perfectly fit the axis distribution function.
b) An MDF between two uniform distributions is itself uniform, independent of the symmetry. 

We may discuss this in Chemnitz soon.

Ralf.
