### ISSUE TITLE
Using V.polar (vector3d)

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#196]
There are atleast 2 ways of getting the spherical polar angles of vector3d V

In previous versions of MTEX and current versions

``` matlab
 [polar_angle,azimuth_angle,radius] = polar(V)
```

In MTEX4 versions you could use

``` matlab
polar_angle_degrees = V.polar/degree
azimuth_angle_degrees = V.rho/degree
```

However in version MTEX 4.4.alpha.5 and possibly earlier versions

``` matlab
polar_angle_degrees = V.polar/degree
```

give an error

```
Error using  ./ 
Not enough input arguments.
```

This is because V.polar now gives both spherical polar angles

```
>V.polar
>polar angle    90.0°
>azimuthal angle   263.6°
```

This is either bug or a change in syntax

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

good you found this. But its hard to eliminate. Actually also in former versions of MTEX
```matlab
V.polar
```
returned 
```
polar angle    90.0°
azimuthal angle   263.6°
```
The reason this became an issue for you is that I implemented 
```matlab
v / 2
```
to divide the vector by a scalar. I did not though that this might have such a strange side effect. Actually, you would get the same error in older MTEX versions with
```matlab
x = V.polar + pi
```
while 
```
x = V.polar; x = x + pi;
```
or
```matlab
x = V.polar; x = x / degree;
```
should work without problem. The above line might be a workaround for you or
```
polar_angle_degrees = V.theta/degree
```
Ralf.

**Comment by DavidMainprice** [comment]
This still works for every version as far as I know
[polar_angle,azimuth_angle,radius] = polar(V)

polar_angle_degrees = V.theta/degree
gives the azimuthal angle in degrees without error

all the best David

**Comment by DavidMainprice** [comment]
[phi,azimuth,~] = polar(V)
With MATLAB 2016a gives a  Message (not an error, so it still works)
Explanation 
An assignment statement makes an assignment to multiple values, but the expression on the right side of the assignment does not appear to produce multiple values.

So I image MATLAB 2016a would prefer V.theta etc

all the best David

**Comment by DavidMainprice** [comment]
Dear Ralf,
this problem is still present in MTEX 4.4.alpha.7
% define polar angles
polar = xxvector.polar/degree
azimuth = xxvector.rho/degree

Error using  / 
Not enough input arguments.
 
    polar angle   90.0°
azimuthal angle    0.0°

all the best David

**Comment by DavidMainprice** [comment]
With MTEX
[theta,rho,r] = polar(vector3d(1,0,0))
Insufficient number of outputs from right hand side of equal sign to satisfy assignment.

**Comment by DavidMainprice** [comment]
I an now using
polar = acos(xvector.z./norm(xxvector))/degree
azimuth = mod(atan2(xvector.y,xvector.x),2*pi)/degree

all the best David
