### ISSUE TITLE
calcGrains() failed in 5.2.1  (until 5.2 it worked)

### ISSUE THREAD

**Issue by accessT** [mtex-toolbox/mtex#432]
For my ebsd-plot:
Untill mtex 5.2 i could use the function calcGrains(). But with 5.2.1 i get this error:

**'
**Undefined function or variable 'qq'.**
Error in quaternion/mean (line 26)
  qm = qq;
Error in quaternion/mean (line 42)
  [qm,lambda, V] = mean(q.subSet(id),varargin{:});
Error in EBSD/calcGrains (line 71)
  mq = mean(qind,'robust');**

the lines in .\mtex-5.2.1\geometry\@quaternion\mean.m:
_if isempty(q)
  qm = quaternion.nan;  
  return
elseif length(q) == 1
  **qm = qq;**
  lambda = diag([0 0 0 1]);
  return
end_
makes it impossible to calc. But when i uncomment them, it works.

so, what is **qq**?

Try it by yourself: 
fullpath='< edithere >'
CS = {'notIndexed', crystalSymmetry('m-3m', 'mineral', 'Ti (beta)'), 'notIndexed'};
ebsd = EBSD.load(**fullpath**,CS,'interface','generic', 'ColumnNames', { 'phi1' 'Phi' 'phi2' 'x' 'y'}, 'Bunge')

This file seems to work: [klick](https://www.dropbox.com/s/xd6eqp3wro40kj2/Probe%201%20TEST%20Specimen%201%20Site%201%20Map%20Data%201%20-%20reconstruction_alpha2beta.txt?dl=1)
but this ebsd file gets with 5.2.1 the error (but works fine untill 5.2): [klick](https://www.dropbox.com/s/v2x3m6re18rpe5d/EDXLMDTi64%20Specimen%201%20M1%20Map%20Data%201%20-%20reconstruction_alpha2beta.txt?dl=1)

**Comment by ralfHielscher** [comment]
Thank you for reporting this. qq is a typo it should by q.

Ralf.

**Comment by accessT** [comment]
> Thank you for reporting this. qq is a typo it should by q.
> 
> Ralf.

Thank you for the hotfix. I've tested 5.2.2. But still cannot plot the second link.  
Just recalculated [them](https://www.dropbox.com/s/5ym064n45tzl0j6/EDXLMDTi64%20Specimen%201%20M1%20Map%20Data%201%20-%20reconstruction_alpha2beta%20recalc_521.txt?dl=1). Seems that all the new calculations (with 5.2+) get a negativ y-coordinate. But untill 5.2 (and below) it can be ploted without problems..

**Comment by ralfHielscher** [comment]
Hi,

thank you for trying MTEX 5.2.2. I hope I have fixed it in the most recent release. 
Your data look very interesting. Do you have a little bit of a story about them? How they are measured? What do they represent? Why are they at such an irregular grid?

Especially because of the last I would like to include them into MTEX as an example data set.

All the best,

Ralf.

**Comment by accessT** [comment]
> Your data look very interesting. Do you have a little bit of a story about them? How they are measured? What do they represent? Why are they at such an irregular grid?

I was using the code from Gerrit-ter-Haar to reconstruct Ti beta (from given Ti alpha) with a threshold of 30 and an angle of 5° (older maybe 15°..). 
Initially, the x-y coordinates were positive at the beginning with mtex 5. Interestingly enough, now I mostly get negative y-coordinate. Must still find out why.

> Especially because of the last I would like to include them into MTEX as an example data set.

when you plot them, the grainsize should be ~100 (pixels).

**Comment by ralfHielscher** [comment]
Hi,
i try to structure my questions more clearly:

1. Does the code of Gerrit-ter-Haar changes x and y coordinates?

**Comment by accessT** [comment]
ad 1) Yes, Now it works. Thank you!
ad 2) [EDXLMDTi64_alpha.zip](https://github.com/mtex-toolbox/mtex/files/3828748/EDXLMDTi64_alpha.zip)
ad 3) untill MTEX 5.1.1 i get positive y-coordinates. With MTEX 5.2.0 - 5.2.3 i get negative y-coordinates... still don't know why.
ad 4) I will discuss it with my team.
ad 5) #todo _going to re-analyse the code and give a feedback later.._

**Comment by accessT** [comment]
>     3. Does the code of Gerrit-ter-Haar changes x and y coordinates? Why?

The problem seems to be while loading the ebsd-file or exporting it: _ebsd = loadEBSD(fullpath,'interface',.crc, 'convertSpatial2EulerReferenceFrame');_
_export(ebsd, 'ebsdTo.txt')_
with MTEX 5.1.1 it works, but with 5.2 + it changes the y-coordinate
Screenshots:
5.1.1 - at line 0
![ebsd_511](https://user-images.githubusercontent.com/57536659/68613901-11f93c80-04c0-11ea-8083-6b08accb50d1.jpg)
5.2.3 - at line 0
![ebsd_523](https://user-images.githubusercontent.com/57536659/68613903-11f93c80-04c0-11ea-9add-46231fc4a3d7.jpg)
5.1.1 - at line 10k
![ebsd_511_10k](https://user-images.githubusercontent.com/57536659/68613902-11f93c80-04c0-11ea-953c-74f0ea621229.jpg)
5.2.3 - at line 10k
![ebsd_523_10k](https://user-images.githubusercontent.com/57536659/68613904-11f93c80-04c0-11ea-9a10-97a90a71d29f.jpg)
